/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarehousesIndexRouteImport } from './routes/warehouses/index'
import { Route as ShipmentsIndexRouteImport } from './routes/shipments/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as PricesIndexRouteImport } from './routes/prices/index'
import { Route as FreeChatIndexRouteImport } from './routes/free-chat/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as ContractorsIndexRouteImport } from './routes/contractors/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as EmployeesEmployeeIdRouteImport } from './routes/employees/$employeeId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProjectsNewIndexRouteImport } from './routes/projects/new/index'
import { Route as ProductsEditIndexRouteImport } from './routes/products/edit/index'
import { Route as ProductsAddIndexRouteImport } from './routes/products/add/index'
import { Route as ProjectsProjectIdEditRouteImport } from './routes/projects/$projectId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesIndexRoute = WarehousesIndexRouteImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsIndexRoute = ShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesIndexRoute = PricesIndexRouteImport.update({
  id: '/prices/',
  path: '/prices/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeChatIndexRoute = FreeChatIndexRouteImport.update({
  id: '/free-chat/',
  path: '/free-chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsIndexRoute = ContractorsIndexRouteImport.update({
  id: '/contractors/',
  path: '/contractors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEmployeeIdRoute = EmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewIndexRoute = ProjectsNewIndexRouteImport.update({
  id: '/projects/new/',
  path: '/projects/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEditIndexRoute = ProductsEditIndexRouteImport.update({
  id: '/products/edit/',
  path: '/products/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAddIndexRoute = ProductsAddIndexRouteImport.update({
  id: '/products/add/',
  path: '/products/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdEditRoute = ProjectsProjectIdEditRouteImport.update({
  id: '/projects/$projectId/edit',
  path: '/projects/$projectId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/contractors/': typeof ContractorsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/free-chat/': typeof FreeChatIndexRoute
  '/prices/': typeof PricesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
  '/warehouses/': typeof WarehousesIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/products/add/': typeof ProductsAddIndexRoute
  '/products/edit/': typeof ProductsEditIndexRoute
  '/projects/new/': typeof ProjectsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/contractors': typeof ContractorsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/free-chat': typeof FreeChatIndexRoute
  '/prices': typeof PricesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/shipments': typeof ShipmentsIndexRoute
  '/warehouses': typeof WarehousesIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/products/add': typeof ProductsAddIndexRoute
  '/products/edit': typeof ProductsEditIndexRoute
  '/projects/new': typeof ProjectsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/contractors/': typeof ContractorsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/free-chat/': typeof FreeChatIndexRoute
  '/prices/': typeof PricesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/shipments/': typeof ShipmentsIndexRoute
  '/warehouses/': typeof WarehousesIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/products/add/': typeof ProductsAddIndexRoute
  '/products/edit/': typeof ProductsEditIndexRoute
  '/projects/new/': typeof ProjectsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/employees/$employeeId'
    | '/products/$productId'
    | '/contractors/'
    | '/employees/'
    | '/free-chat/'
    | '/prices/'
    | '/products/'
    | '/projects/'
    | '/shipments/'
    | '/warehouses/'
    | '/projects/$projectId/edit'
    | '/products/add/'
    | '/products/edit/'
    | '/projects/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/employees/$employeeId'
    | '/products/$productId'
    | '/contractors'
    | '/employees'
    | '/free-chat'
    | '/prices'
    | '/products'
    | '/projects'
    | '/shipments'
    | '/warehouses'
    | '/projects/$projectId/edit'
    | '/products/add'
    | '/products/edit'
    | '/projects/new'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/employees/$employeeId'
    | '/products/$productId'
    | '/contractors/'
    | '/employees/'
    | '/free-chat/'
    | '/prices/'
    | '/products/'
    | '/projects/'
    | '/shipments/'
    | '/warehouses/'
    | '/projects/$projectId/edit'
    | '/products/add/'
    | '/products/edit/'
    | '/projects/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ContractorsIndexRoute: typeof ContractorsIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  FreeChatIndexRoute: typeof FreeChatIndexRoute
  PricesIndexRoute: typeof PricesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ShipmentsIndexRoute: typeof ShipmentsIndexRoute
  WarehousesIndexRoute: typeof WarehousesIndexRoute
  ProjectsProjectIdEditRoute: typeof ProjectsProjectIdEditRoute
  ProductsAddIndexRoute: typeof ProductsAddIndexRoute
  ProductsEditIndexRoute: typeof ProductsEditIndexRoute
  ProjectsNewIndexRoute: typeof ProjectsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses/': {
      id: '/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof WarehousesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/': {
      id: '/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof ShipmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices/': {
      id: '/prices/'
      path: '/prices'
      fullPath: '/prices/'
      preLoaderRoute: typeof PricesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-chat/': {
      id: '/free-chat/'
      path: '/free-chat'
      fullPath: '/free-chat/'
      preLoaderRoute: typeof FreeChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors/': {
      id: '/contractors/'
      path: '/contractors'
      fullPath: '/contractors/'
      preLoaderRoute: typeof ContractorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new/': {
      id: '/projects/new/'
      path: '/projects/new'
      fullPath: '/projects/new/'
      preLoaderRoute: typeof ProjectsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/edit/': {
      id: '/products/edit/'
      path: '/products/edit'
      fullPath: '/products/edit/'
      preLoaderRoute: typeof ProductsEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/add/': {
      id: '/products/add/'
      path: '/products/add'
      fullPath: '/products/add/'
      preLoaderRoute: typeof ProductsAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/edit': {
      id: '/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProjectsProjectIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ContractorsIndexRoute: ContractorsIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  FreeChatIndexRoute: FreeChatIndexRoute,
  PricesIndexRoute: PricesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ShipmentsIndexRoute: ShipmentsIndexRoute,
  WarehousesIndexRoute: WarehousesIndexRoute,
  ProjectsProjectIdEditRoute: ProjectsProjectIdEditRoute,
  ProductsAddIndexRoute: ProductsAddIndexRoute,
  ProductsEditIndexRoute: ProductsEditIndexRoute,
  ProjectsNewIndexRoute: ProjectsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
